version: 2

build:
  image: latest

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

formats: []

sphinx:
  builder: html
  configuration: docs/conf.py
